dbcond.o: dbcond.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../include/dbcond.h \
  ../../dcmnet/include/dicom.h ../../ofstd/include/ofstdinc.h \
  ../../dcmnet/include/cond.h ../../ofstd/include/ofconsol.h \
  ../../ofstd/include/ofstream.h ../../ofstd/include/ofthread.h \
  ../../ofstd/include/oftypes.h ../../ofstd/include/ofstring.h \
  ../../ofstd/include/ofcast.h ../../dcmdata/include/dcerror.h \
  ../../ofstd/include/ofcond.h ../../dcmnet/include/dcompat.h \
  ../../ofstd/include/ofbmanip.h ../../dcmdata/include/dctypes.h \
  ../../dcmdata/include/dcuid.h
dbfind.o: dbfind.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../../ofstd/include/ofstdinc.h \
  ../include/imagedb.h ../../dcmnet/include/dicom.h \
  ../../dcmnet/include/cond.h ../../ofstd/include/ofconsol.h \
  ../../ofstd/include/ofstream.h ../../ofstd/include/ofthread.h \
  ../../ofstd/include/oftypes.h ../../ofstd/include/ofstring.h \
  ../../ofstd/include/ofcast.h ../../dcmdata/include/dcerror.h \
  ../../ofstd/include/ofcond.h ../../dcmnet/include/dcompat.h \
  ../../ofstd/include/ofbmanip.h ../../dcmdata/include/dctypes.h \
  ../../dcmdata/include/dcuid.h ../../dcmdata/include/dcdatset.h \
  ../../dcmdata/include/dcitem.h ../../dcmdata/include/dcobject.h \
  ../../ofstd/include/ofglobal.h ../../dcmdata/include/dcxfer.h \
  ../../dcmdata/include/dcvr.h ../../dcmdata/include/dctag.h \
  ../../dcmdata/include/dctagkey.h ../../dcmdata/include/dclist.h \
  ../../dcmdata/include/dcstack.h ../../dcmdata/include/dcvrui.h \
  ../../dcmdata/include/dcbytstr.h ../../dcmdata/include/dcelem.h \
  ../../dcmdata/include/dcpcache.h ../../ofstd/include/oflist.h \
  ../../dcmnet/include/dimse.h ../../dcmnet/include/lst.h \
  ../../dcmnet/include/dul.h ../../dcmnet/include/extneg.h \
  ../../dcmnet/include/assoc.h ../include/dbpriv.h \
  ../../dcmdata/include/dcdeftag.h ../../dcmnet/include/diutil.h \
  ../include/dbcond.h
dbindex.o: dbindex.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../../ofstd/include/ofstdinc.h \
  ../include/imagedb.h ../../dcmnet/include/dicom.h \
  ../../dcmnet/include/cond.h ../../ofstd/include/ofconsol.h \
  ../../ofstd/include/ofstream.h ../../ofstd/include/ofthread.h \
  ../../ofstd/include/oftypes.h ../../ofstd/include/ofstring.h \
  ../../ofstd/include/ofcast.h ../../dcmdata/include/dcerror.h \
  ../../ofstd/include/ofcond.h ../../dcmnet/include/dcompat.h \
  ../../ofstd/include/ofbmanip.h ../../dcmdata/include/dctypes.h \
  ../../dcmdata/include/dcuid.h ../../dcmdata/include/dcdatset.h \
  ../../dcmdata/include/dcitem.h ../../dcmdata/include/dcobject.h \
  ../../ofstd/include/ofglobal.h ../../dcmdata/include/dcxfer.h \
  ../../dcmdata/include/dcvr.h ../../dcmdata/include/dctag.h \
  ../../dcmdata/include/dctagkey.h ../../dcmdata/include/dclist.h \
  ../../dcmdata/include/dcstack.h ../../dcmdata/include/dcvrui.h \
  ../../dcmdata/include/dcbytstr.h ../../dcmdata/include/dcelem.h \
  ../../dcmdata/include/dcpcache.h ../../ofstd/include/oflist.h \
  ../../dcmnet/include/dimse.h ../../dcmnet/include/lst.h \
  ../../dcmnet/include/dul.h ../../dcmnet/include/extneg.h \
  ../../dcmnet/include/assoc.h ../include/dbpriv.h \
  ../../dcmdata/include/dcdeftag.h ../include/dbcond.h
dbmove.o: dbmove.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../../ofstd/include/ofstdinc.h \
  ../include/imagedb.h ../../dcmnet/include/dicom.h \
  ../../dcmnet/include/cond.h ../../ofstd/include/ofconsol.h \
  ../../ofstd/include/ofstream.h ../../ofstd/include/ofthread.h \
  ../../ofstd/include/oftypes.h ../../ofstd/include/ofstring.h \
  ../../ofstd/include/ofcast.h ../../dcmdata/include/dcerror.h \
  ../../ofstd/include/ofcond.h ../../dcmnet/include/dcompat.h \
  ../../ofstd/include/ofbmanip.h ../../dcmdata/include/dctypes.h \
  ../../dcmdata/include/dcuid.h ../../dcmdata/include/dcdatset.h \
  ../../dcmdata/include/dcitem.h ../../dcmdata/include/dcobject.h \
  ../../ofstd/include/ofglobal.h ../../dcmdata/include/dcxfer.h \
  ../../dcmdata/include/dcvr.h ../../dcmdata/include/dctag.h \
  ../../dcmdata/include/dctagkey.h ../../dcmdata/include/dclist.h \
  ../../dcmdata/include/dcstack.h ../../dcmdata/include/dcvrui.h \
  ../../dcmdata/include/dcbytstr.h ../../dcmdata/include/dcelem.h \
  ../../dcmdata/include/dcpcache.h ../../ofstd/include/oflist.h \
  ../../dcmnet/include/dimse.h ../../dcmnet/include/lst.h \
  ../../dcmnet/include/dul.h ../../dcmnet/include/extneg.h \
  ../../dcmnet/include/assoc.h ../include/dbpriv.h \
  ../../dcmdata/include/dcdeftag.h ../include/dbcond.h
dbstore.o: dbstore.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../../ofstd/include/ofstdinc.h \
  ../../dcmnet/include/dcompat.h ../../ofstd/include/ofbmanip.h \
  ../../ofstd/include/ofcast.h ../include/imagedb.h \
  ../../dcmnet/include/dicom.h ../../dcmnet/include/cond.h \
  ../../ofstd/include/ofconsol.h ../../ofstd/include/ofstream.h \
  ../../ofstd/include/ofthread.h ../../ofstd/include/oftypes.h \
  ../../ofstd/include/ofstring.h ../../dcmdata/include/dcerror.h \
  ../../ofstd/include/ofcond.h ../../dcmdata/include/dctypes.h \
  ../../dcmdata/include/dcuid.h ../../dcmdata/include/dcdatset.h \
  ../../dcmdata/include/dcitem.h ../../dcmdata/include/dcobject.h \
  ../../ofstd/include/ofglobal.h ../../dcmdata/include/dcxfer.h \
  ../../dcmdata/include/dcvr.h ../../dcmdata/include/dctag.h \
  ../../dcmdata/include/dctagkey.h ../../dcmdata/include/dclist.h \
  ../../dcmdata/include/dcstack.h ../../dcmdata/include/dcvrui.h \
  ../../dcmdata/include/dcbytstr.h ../../dcmdata/include/dcelem.h \
  ../../dcmdata/include/dcpcache.h ../../ofstd/include/oflist.h \
  ../../dcmnet/include/dimse.h ../../dcmnet/include/lst.h \
  ../../dcmnet/include/dul.h ../../dcmnet/include/extneg.h \
  ../../dcmnet/include/assoc.h ../include/dbpriv.h \
  ../../dcmdata/include/dcdeftag.h ../../dcmdata/include/dcfilefo.h \
  ../../dcmdata/include/dcsequen.h ../include/dbcond.h
dbutils.o: dbutils.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../../ofstd/include/ofstdinc.h \
  ../include/imagedb.h ../../dcmnet/include/dicom.h \
  ../../dcmnet/include/cond.h ../../ofstd/include/ofconsol.h \
  ../../ofstd/include/ofstream.h ../../ofstd/include/ofthread.h \
  ../../ofstd/include/oftypes.h ../../ofstd/include/ofstring.h \
  ../../ofstd/include/ofcast.h ../../dcmdata/include/dcerror.h \
  ../../ofstd/include/ofcond.h ../../dcmnet/include/dcompat.h \
  ../../ofstd/include/ofbmanip.h ../../dcmdata/include/dctypes.h \
  ../../dcmdata/include/dcuid.h ../../dcmdata/include/dcdatset.h \
  ../../dcmdata/include/dcitem.h ../../dcmdata/include/dcobject.h \
  ../../ofstd/include/ofglobal.h ../../dcmdata/include/dcxfer.h \
  ../../dcmdata/include/dcvr.h ../../dcmdata/include/dctag.h \
  ../../dcmdata/include/dctagkey.h ../../dcmdata/include/dclist.h \
  ../../dcmdata/include/dcstack.h ../../dcmdata/include/dcvrui.h \
  ../../dcmdata/include/dcbytstr.h ../../dcmdata/include/dcelem.h \
  ../../dcmdata/include/dcpcache.h ../../ofstd/include/oflist.h \
  ../../dcmnet/include/dimse.h ../../dcmnet/include/lst.h \
  ../../dcmnet/include/dul.h ../../dcmnet/include/extneg.h \
  ../../dcmnet/include/assoc.h ../include/dbpriv.h \
  ../../dcmdata/include/dcdeftag.h ../../dcmnet/include/diutil.h \
  ../../ofstd/include/offname.h ../../ofstd/include/ofstd.h \
  ../include/dbcond.h
