cnf.o: cnf.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../../ofstd/include/ofstdinc.h cnfpriv.h \
  ../../ofstd/include/ofcmdln.h ../../ofstd/include/oftypes.h \
  ../../ofstd/include/oflist.h ../../ofstd/include/ofcast.h \
  ../../ofstd/include/ofstring.h ../../ofstd/include/ofstream.h \
  ../../ofstd/include/ofconsol.h ../../ofstd/include/ofthread.h cnf.h
cnfexnt.o: cnfexnt.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../../ofstd/include/ofstdinc.h cnfpriv.h \
  ../../ofstd/include/ofcmdln.h ../../ofstd/include/oftypes.h \
  ../../ofstd/include/oflist.h ../../ofstd/include/ofcast.h \
  ../../ofstd/include/ofstring.h ../../ofstd/include/ofstream.h \
  ../../ofstd/include/ofconsol.h ../../ofstd/include/ofthread.h cnf.h
cnfpriv.o: cnfpriv.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../../ofstd/include/ofstdinc.h cnfpriv.h \
  ../../ofstd/include/ofcmdln.h ../../ofstd/include/oftypes.h \
  ../../ofstd/include/oflist.h ../../ofstd/include/ofcast.h \
  ../../ofstd/include/ofstring.h ../../ofstd/include/ofstream.h \
  ../../ofstd/include/ofconsol.h ../../ofstd/include/ofthread.h
dbregimg.o: dbregimg.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../../ofstd/include/ofstdinc.h \
  ../../dcmnet/include/dicom.h ../../dcmnet/include/cond.h \
  ../../ofstd/include/ofconsol.h ../../ofstd/include/ofstream.h \
  ../../ofstd/include/ofthread.h ../../ofstd/include/oftypes.h \
  ../../ofstd/include/ofstring.h ../../ofstd/include/ofcast.h \
  ../../dcmdata/include/dcerror.h ../../ofstd/include/ofcond.h \
  ../../dcmnet/include/dcompat.h ../../ofstd/include/ofbmanip.h \
  ../../dcmdata/include/dctypes.h ../../dcmdata/include/dcuid.h \
  ../include/imagedb.h ../../dcmdata/include/dcdatset.h \
  ../../dcmdata/include/dcitem.h ../../dcmdata/include/dcobject.h \
  ../../ofstd/include/ofglobal.h ../../dcmdata/include/dcxfer.h \
  ../../dcmdata/include/dcvr.h ../../dcmdata/include/dctag.h \
  ../../dcmdata/include/dctagkey.h ../../dcmdata/include/dclist.h \
  ../../dcmdata/include/dcstack.h ../../dcmdata/include/dcvrui.h \
  ../../dcmdata/include/dcbytstr.h ../../dcmdata/include/dcelem.h \
  ../../dcmdata/include/dcpcache.h ../../ofstd/include/oflist.h \
  ../../dcmnet/include/dimse.h ../../dcmnet/include/lst.h \
  ../../dcmnet/include/dul.h ../../dcmnet/include/extneg.h \
  ../../dcmnet/include/assoc.h ../../dcmnet/include/diutil.h \
  ../../dcmdata/include/dcdebug.h ../../dcmdata/include/dcdict.h \
  ../../dcmdata/include/dchashdi.h ../../dcmdata/include/cmdlnarg.h \
  ../../ofstd/include/ofconapp.h ../../ofstd/include/ofcmdln.h
imagectn.o: imagectn.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../../ofstd/include/ofstdinc.h \
  ../../dcmnet/include/dicom.h ../../dcmnet/include/cond.h \
  ../../ofstd/include/ofconsol.h ../../ofstd/include/ofstream.h \
  ../../ofstd/include/ofthread.h ../../ofstd/include/oftypes.h \
  ../../ofstd/include/ofstring.h ../../ofstd/include/ofcast.h \
  ../../dcmdata/include/dcerror.h ../../ofstd/include/ofcond.h \
  ../../dcmnet/include/dcompat.h ../../ofstd/include/ofbmanip.h \
  ../../dcmdata/include/dctypes.h ../../dcmdata/include/dcuid.h \
  imagectn.h ../../dcmdata/include/dcxfer.h ../../dcmdata/include/dcvr.h \
  ../../ofstd/include/ofglobal.h ../../dcmnet/include/assoc.h \
  ../../dcmnet/include/lst.h ../../ofstd/include/oflist.h \
  ../../dcmnet/include/dul.h ../../dcmnet/include/extneg.h cnf.h \
  ../../ofstd/include/ofcmdln.h ../../ofstd/include/ofconapp.h \
  ../../dcmnet/include/dimse.h ../../dcmdata/include/dcdatset.h \
  ../../dcmdata/include/dcitem.h ../../dcmdata/include/dcobject.h \
  ../../dcmdata/include/dctag.h ../../dcmdata/include/dctagkey.h \
  ../../dcmdata/include/dclist.h ../../dcmdata/include/dcstack.h \
  ../../dcmdata/include/dcvrui.h ../../dcmdata/include/dcbytstr.h \
  ../../dcmdata/include/dcelem.h ../../dcmdata/include/dcpcache.h sce.h \
  ../include/imagedb.h ../../dcmdata/include/dcdict.h \
  ../../dcmdata/include/dchashdi.h ../../dcmdata/include/dcdebug.h \
  ../../dcmdata/include/cmdlnarg.h
sce.o: sce.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../../ofstd/include/ofstdinc.h \
  ../../dcmnet/include/dicom.h ../../dcmnet/include/cond.h \
  ../../ofstd/include/ofconsol.h ../../ofstd/include/ofstream.h \
  ../../ofstd/include/ofthread.h ../../ofstd/include/oftypes.h \
  ../../ofstd/include/ofstring.h ../../ofstd/include/ofcast.h \
  ../../dcmdata/include/dcerror.h ../../ofstd/include/ofcond.h \
  ../../dcmnet/include/dcompat.h ../../ofstd/include/ofbmanip.h \
  ../../dcmdata/include/dctypes.h ../../dcmdata/include/dcuid.h \
  imagectn.h ../../dcmdata/include/dcxfer.h ../../dcmdata/include/dcvr.h \
  ../../ofstd/include/ofglobal.h ../../dcmnet/include/assoc.h \
  ../../dcmnet/include/lst.h ../../ofstd/include/oflist.h \
  ../../dcmnet/include/dul.h ../../dcmnet/include/extneg.h cnf.h \
  ../../ofstd/include/ofcmdln.h ../../ofstd/include/ofconapp.h \
  ../../dcmnet/include/dimse.h ../../dcmdata/include/dcdatset.h \
  ../../dcmdata/include/dcitem.h ../../dcmdata/include/dcobject.h \
  ../../dcmdata/include/dctag.h ../../dcmdata/include/dctagkey.h \
  ../../dcmdata/include/dclist.h ../../dcmdata/include/dcstack.h \
  ../../dcmdata/include/dcvrui.h ../../dcmdata/include/dcbytstr.h \
  ../../dcmdata/include/dcelem.h ../../dcmdata/include/dcpcache.h \
  ../../dcmnet/include/diutil.h sce.h ../include/imagedb.h sceecho.h \
  scestore.h scefind.h scemove.h sceget.h
sceecho.o: sceecho.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../../ofstd/include/ofstdinc.h \
  ../../dcmnet/include/dicom.h ../../dcmnet/include/cond.h \
  ../../ofstd/include/ofconsol.h ../../ofstd/include/ofstream.h \
  ../../ofstd/include/ofthread.h ../../ofstd/include/oftypes.h \
  ../../ofstd/include/ofstring.h ../../ofstd/include/ofcast.h \
  ../../dcmdata/include/dcerror.h ../../ofstd/include/ofcond.h \
  ../../dcmnet/include/dcompat.h ../../ofstd/include/ofbmanip.h \
  ../../dcmdata/include/dctypes.h ../../dcmdata/include/dcuid.h \
  imagectn.h ../../dcmdata/include/dcxfer.h ../../dcmdata/include/dcvr.h \
  ../../ofstd/include/ofglobal.h ../../dcmnet/include/assoc.h \
  ../../dcmnet/include/lst.h ../../ofstd/include/oflist.h \
  ../../dcmnet/include/dul.h ../../dcmnet/include/extneg.h cnf.h \
  ../../ofstd/include/ofcmdln.h ../../ofstd/include/ofconapp.h \
  ../../dcmnet/include/dimse.h ../../dcmdata/include/dcdatset.h \
  ../../dcmdata/include/dcitem.h ../../dcmdata/include/dcobject.h \
  ../../dcmdata/include/dctag.h ../../dcmdata/include/dctagkey.h \
  ../../dcmdata/include/dclist.h ../../dcmdata/include/dcstack.h \
  ../../dcmdata/include/dcvrui.h ../../dcmdata/include/dcbytstr.h \
  ../../dcmdata/include/dcelem.h ../../dcmdata/include/dcpcache.h \
  sceecho.h
scefind.o: scefind.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../../ofstd/include/ofstdinc.h \
  ../../dcmnet/include/dicom.h ../../dcmnet/include/cond.h \
  ../../ofstd/include/ofconsol.h ../../ofstd/include/ofstream.h \
  ../../ofstd/include/ofthread.h ../../ofstd/include/oftypes.h \
  ../../ofstd/include/ofstring.h ../../ofstd/include/ofcast.h \
  ../../dcmdata/include/dcerror.h ../../ofstd/include/ofcond.h \
  ../../dcmnet/include/dcompat.h ../../ofstd/include/ofbmanip.h \
  ../../dcmdata/include/dctypes.h ../../dcmdata/include/dcuid.h \
  imagectn.h ../../dcmdata/include/dcxfer.h ../../dcmdata/include/dcvr.h \
  ../../ofstd/include/ofglobal.h ../../dcmnet/include/assoc.h \
  ../../dcmnet/include/lst.h ../../ofstd/include/oflist.h \
  ../../dcmnet/include/dul.h ../../dcmnet/include/extneg.h cnf.h \
  ../../ofstd/include/ofcmdln.h ../../ofstd/include/ofconapp.h \
  ../../dcmnet/include/dimse.h ../../dcmdata/include/dcdatset.h \
  ../../dcmdata/include/dcitem.h ../../dcmdata/include/dcobject.h \
  ../../dcmdata/include/dctag.h ../../dcmdata/include/dctagkey.h \
  ../../dcmdata/include/dclist.h ../../dcmdata/include/dcstack.h \
  ../../dcmdata/include/dcvrui.h ../../dcmdata/include/dcbytstr.h \
  ../../dcmdata/include/dcelem.h ../../dcmdata/include/dcpcache.h \
  ../../dcmnet/include/diutil.h sce.h ../include/imagedb.h \
  ../../dcmdata/include/dcdeftag.h scefind.h
sceget.o: sceget.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../../ofstd/include/ofstdinc.h \
  ../../dcmnet/include/dicom.h ../../dcmnet/include/cond.h \
  ../../ofstd/include/ofconsol.h ../../ofstd/include/ofstream.h \
  ../../ofstd/include/ofthread.h ../../ofstd/include/oftypes.h \
  ../../ofstd/include/ofstring.h ../../ofstd/include/ofcast.h \
  ../../dcmdata/include/dcerror.h ../../ofstd/include/ofcond.h \
  ../../dcmnet/include/dcompat.h ../../ofstd/include/ofbmanip.h \
  ../../dcmdata/include/dctypes.h ../../dcmdata/include/dcuid.h \
  imagectn.h ../../dcmdata/include/dcxfer.h ../../dcmdata/include/dcvr.h \
  ../../ofstd/include/ofglobal.h ../../dcmnet/include/assoc.h \
  ../../dcmnet/include/lst.h ../../ofstd/include/oflist.h \
  ../../dcmnet/include/dul.h ../../dcmnet/include/extneg.h cnf.h \
  ../../ofstd/include/ofcmdln.h ../../ofstd/include/ofconapp.h \
  ../../dcmnet/include/dimse.h ../../dcmdata/include/dcdatset.h \
  ../../dcmdata/include/dcitem.h ../../dcmdata/include/dcobject.h \
  ../../dcmdata/include/dctag.h ../../dcmdata/include/dctagkey.h \
  ../../dcmdata/include/dclist.h ../../dcmdata/include/dcstack.h \
  ../../dcmdata/include/dcvrui.h ../../dcmdata/include/dcbytstr.h \
  ../../dcmdata/include/dcelem.h ../../dcmdata/include/dcpcache.h \
  ../../dcmnet/include/diutil.h sce.h ../include/imagedb.h \
  ../../dcmdata/include/dcdeftag.h sceget.h
scemove.o: scemove.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../../ofstd/include/ofstdinc.h \
  ../../dcmnet/include/dicom.h ../../dcmnet/include/cond.h \
  ../../ofstd/include/ofconsol.h ../../ofstd/include/ofstream.h \
  ../../ofstd/include/ofthread.h ../../ofstd/include/oftypes.h \
  ../../ofstd/include/ofstring.h ../../ofstd/include/ofcast.h \
  ../../dcmdata/include/dcerror.h ../../ofstd/include/ofcond.h \
  ../../dcmnet/include/dcompat.h ../../ofstd/include/ofbmanip.h \
  ../../dcmdata/include/dctypes.h ../../dcmdata/include/dcuid.h \
  imagectn.h ../../dcmdata/include/dcxfer.h ../../dcmdata/include/dcvr.h \
  ../../ofstd/include/ofglobal.h ../../dcmnet/include/assoc.h \
  ../../dcmnet/include/lst.h ../../ofstd/include/oflist.h \
  ../../dcmnet/include/dul.h ../../dcmnet/include/extneg.h cnf.h \
  ../../ofstd/include/ofcmdln.h ../../ofstd/include/ofconapp.h \
  ../../dcmnet/include/dimse.h ../../dcmdata/include/dcdatset.h \
  ../../dcmdata/include/dcitem.h ../../dcmdata/include/dcobject.h \
  ../../dcmdata/include/dctag.h ../../dcmdata/include/dctagkey.h \
  ../../dcmdata/include/dclist.h ../../dcmdata/include/dcstack.h \
  ../../dcmdata/include/dcvrui.h ../../dcmdata/include/dcbytstr.h \
  ../../dcmdata/include/dcelem.h ../../dcmdata/include/dcpcache.h \
  ../../dcmnet/include/diutil.h sce.h ../include/imagedb.h \
  ../../dcmdata/include/dcdeftag.h scemove.h
scestore.o: scestore.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../../ofstd/include/ofstdinc.h \
  ../../dcmnet/include/dicom.h ../../dcmnet/include/cond.h \
  ../../ofstd/include/ofconsol.h ../../ofstd/include/ofstream.h \
  ../../ofstd/include/ofthread.h ../../ofstd/include/oftypes.h \
  ../../ofstd/include/ofstring.h ../../ofstd/include/ofcast.h \
  ../../dcmdata/include/dcerror.h ../../ofstd/include/ofcond.h \
  ../../dcmnet/include/dcompat.h ../../ofstd/include/ofbmanip.h \
  ../../dcmdata/include/dctypes.h ../../dcmdata/include/dcuid.h \
  imagectn.h ../../dcmdata/include/dcxfer.h ../../dcmdata/include/dcvr.h \
  ../../ofstd/include/ofglobal.h ../../dcmnet/include/assoc.h \
  ../../dcmnet/include/lst.h ../../ofstd/include/oflist.h \
  ../../dcmnet/include/dul.h ../../dcmnet/include/extneg.h cnf.h \
  ../../ofstd/include/ofcmdln.h ../../ofstd/include/ofconapp.h \
  ../../dcmnet/include/dimse.h ../../dcmdata/include/dcdatset.h \
  ../../dcmdata/include/dcitem.h ../../dcmdata/include/dcobject.h \
  ../../dcmdata/include/dctag.h ../../dcmdata/include/dctagkey.h \
  ../../dcmdata/include/dclist.h ../../dcmdata/include/dcstack.h \
  ../../dcmdata/include/dcvrui.h ../../dcmdata/include/dcbytstr.h \
  ../../dcmdata/include/dcelem.h ../../dcmdata/include/dcpcache.h \
  ../../dcmnet/include/diutil.h sce.h ../include/imagedb.h \
  ../../dcmdata/include/dcfilefo.h ../../dcmdata/include/dcsequen.h \
  scestore.h
ti.o: ti.cc ../../config/include/osconfig.h ../../config/include/cfunix.h \
  ../../ofstd/include/ofstdinc.h ti.h ../../dcmnet/include/dicom.h \
  ../../dcmnet/include/cond.h ../../ofstd/include/ofconsol.h \
  ../../ofstd/include/ofstream.h ../../ofstd/include/ofthread.h \
  ../../ofstd/include/oftypes.h ../../ofstd/include/ofstring.h \
  ../../ofstd/include/ofcast.h ../../dcmdata/include/dcerror.h \
  ../../ofstd/include/ofcond.h ../../dcmnet/include/dcompat.h \
  ../../ofstd/include/ofbmanip.h ../../dcmdata/include/dctypes.h \
  ../../dcmdata/include/dcuid.h ../../dcmnet/include/assoc.h \
  ../../dcmnet/include/lst.h ../../ofstd/include/oflist.h \
  ../../dcmnet/include/dul.h ../../ofstd/include/ofglobal.h \
  ../../dcmnet/include/extneg.h ../../dcmnet/include/dimse.h \
  ../../dcmdata/include/dcdatset.h ../../dcmdata/include/dcitem.h \
  ../../dcmdata/include/dcobject.h ../../dcmdata/include/dcxfer.h \
  ../../dcmdata/include/dcvr.h ../../dcmdata/include/dctag.h \
  ../../dcmdata/include/dctagkey.h ../../dcmdata/include/dclist.h \
  ../../dcmdata/include/dcstack.h ../../dcmdata/include/dcvrui.h \
  ../../dcmdata/include/dcbytstr.h ../../dcmdata/include/dcelem.h \
  ../../dcmdata/include/dcpcache.h ../../ofstd/include/ofcmdln.h cnf.h \
  ../include/imagedb.h ../../dcmdata/include/dcdict.h \
  ../../dcmdata/include/dchashdi.h ../../dcmdata/include/cmdlnarg.h \
  ../../dcmdata/include/dcdebug.h tiui.h tinet.h tiquery.h \
  ../../dcmnet/include/diutil.h ../../ofstd/include/ofconapp.h
tinet.o: tinet.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../../ofstd/include/ofstdinc.h ti.h \
  ../../dcmnet/include/dicom.h ../../dcmnet/include/cond.h \
  ../../ofstd/include/ofconsol.h ../../ofstd/include/ofstream.h \
  ../../ofstd/include/ofthread.h ../../ofstd/include/oftypes.h \
  ../../ofstd/include/ofstring.h ../../ofstd/include/ofcast.h \
  ../../dcmdata/include/dcerror.h ../../ofstd/include/ofcond.h \
  ../../dcmnet/include/dcompat.h ../../ofstd/include/ofbmanip.h \
  ../../dcmdata/include/dctypes.h ../../dcmdata/include/dcuid.h \
  ../../dcmnet/include/assoc.h ../../dcmnet/include/lst.h \
  ../../ofstd/include/oflist.h ../../dcmnet/include/dul.h \
  ../../ofstd/include/ofglobal.h ../../dcmnet/include/extneg.h \
  ../../dcmnet/include/dimse.h ../../dcmdata/include/dcdatset.h \
  ../../dcmdata/include/dcitem.h ../../dcmdata/include/dcobject.h \
  ../../dcmdata/include/dcxfer.h ../../dcmdata/include/dcvr.h \
  ../../dcmdata/include/dctag.h ../../dcmdata/include/dctagkey.h \
  ../../dcmdata/include/dclist.h ../../dcmdata/include/dcstack.h \
  ../../dcmdata/include/dcvrui.h ../../dcmdata/include/dcbytstr.h \
  ../../dcmdata/include/dcelem.h ../../dcmdata/include/dcpcache.h \
  ../../ofstd/include/ofcmdln.h cnf.h ../include/imagedb.h \
  ../../dcmnet/include/diutil.h ../../dcmdata/include/dcfilefo.h \
  ../../dcmdata/include/dcsequen.h tiui.h tiquery.h tinet.h
tiquery.o: tiquery.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../../ofstd/include/ofstdinc.h ti.h \
  ../../dcmnet/include/dicom.h ../../dcmnet/include/cond.h \
  ../../ofstd/include/ofconsol.h ../../ofstd/include/ofstream.h \
  ../../ofstd/include/ofthread.h ../../ofstd/include/oftypes.h \
  ../../ofstd/include/ofstring.h ../../ofstd/include/ofcast.h \
  ../../dcmdata/include/dcerror.h ../../ofstd/include/ofcond.h \
  ../../dcmnet/include/dcompat.h ../../ofstd/include/ofbmanip.h \
  ../../dcmdata/include/dctypes.h ../../dcmdata/include/dcuid.h \
  ../../dcmnet/include/assoc.h ../../dcmnet/include/lst.h \
  ../../ofstd/include/oflist.h ../../dcmnet/include/dul.h \
  ../../ofstd/include/ofglobal.h ../../dcmnet/include/extneg.h \
  ../../dcmnet/include/dimse.h ../../dcmdata/include/dcdatset.h \
  ../../dcmdata/include/dcitem.h ../../dcmdata/include/dcobject.h \
  ../../dcmdata/include/dcxfer.h ../../dcmdata/include/dcvr.h \
  ../../dcmdata/include/dctag.h ../../dcmdata/include/dctagkey.h \
  ../../dcmdata/include/dclist.h ../../dcmdata/include/dcstack.h \
  ../../dcmdata/include/dcvrui.h ../../dcmdata/include/dcbytstr.h \
  ../../dcmdata/include/dcelem.h ../../dcmdata/include/dcpcache.h \
  ../../ofstd/include/ofcmdln.h cnf.h ../include/imagedb.h \
  ../../dcmnet/include/diutil.h ../../dcmdata/include/dcdeftag.h \
  ../../dcmdata/include/dcfilefo.h ../../dcmdata/include/dcsequen.h \
  tiquery.h tinet.h tiui.h
tiui.o: tiui.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../../ofstd/include/ofstdinc.h ti.h \
  ../../dcmnet/include/dicom.h ../../dcmnet/include/cond.h \
  ../../ofstd/include/ofconsol.h ../../ofstd/include/ofstream.h \
  ../../ofstd/include/ofthread.h ../../ofstd/include/oftypes.h \
  ../../ofstd/include/ofstring.h ../../ofstd/include/ofcast.h \
  ../../dcmdata/include/dcerror.h ../../ofstd/include/ofcond.h \
  ../../dcmnet/include/dcompat.h ../../ofstd/include/ofbmanip.h \
  ../../dcmdata/include/dctypes.h ../../dcmdata/include/dcuid.h \
  ../../dcmnet/include/assoc.h ../../dcmnet/include/lst.h \
  ../../ofstd/include/oflist.h ../../dcmnet/include/dul.h \
  ../../ofstd/include/ofglobal.h ../../dcmnet/include/extneg.h \
  ../../dcmnet/include/dimse.h ../../dcmdata/include/dcdatset.h \
  ../../dcmdata/include/dcitem.h ../../dcmdata/include/dcobject.h \
  ../../dcmdata/include/dcxfer.h ../../dcmdata/include/dcvr.h \
  ../../dcmdata/include/dctag.h ../../dcmdata/include/dctagkey.h \
  ../../dcmdata/include/dclist.h ../../dcmdata/include/dcstack.h \
  ../../dcmdata/include/dcvrui.h ../../dcmdata/include/dcbytstr.h \
  ../../dcmdata/include/dcelem.h ../../dcmdata/include/dcpcache.h \
  ../../ofstd/include/ofcmdln.h cnf.h ../include/imagedb.h \
  ../../dcmdata/include/dcdeftag.h ../../dcmnet/include/diutil.h tiui.h \
  tinet.h tiquery.h
